### ISSUE TITLE
能否给下excel的格式

### ISSUE THREAD

**Issue by ghost** [IoTChainCode/TokenAirdrop#1]
我尝试调试格式失败，您提供的list 里面没有标准的格式。

**Comment by saber-yy** [comment]
这是需要根据具体文档格式来解析的，调整airdropList.js中的addressIndex的值来解析空投地址列表。你可以参考项目中itc_airdrop_total.xlsx。

**Comment by ghost** [comment]
测试完成了。调通了发现几个问题：
1. 超过50个list就不会继续发送了。
2. 强制amount * 18 有问题的

**Comment by saber-yy** [comment]
回复问题1:这个也是看你这边的需求来设置的。这份代码里面是设置的最大空投数量为50，方便统计。你可以修改airdropList.js中的maxLength属性来修改。airdropList.js中的destinationStartIndex是此次空投起始的序号。
回复问题2:你要看amount是什么属性的变量。数字类型的*18才有意义。

**Comment by ghost** [comment]
我测试过airdropper的合约 最大容量应该是250左右，超过了就需要发起二次调用啦。

**Comment by ghost** [comment]
我的意思是不是所有的token的位数都是18位 你里面写死18位，转账可能会有一定的问题~

**Comment by saber-yy** [comment]
之前查阅到的以太坊的生成规则是：公钥去掉开头04，剩下的进行keccak-256的哈希，得到长度64的16进制字串，丢掉前面24个，拿后40个，再加上"0x"；
还有其他的以太坊地址生成规则吗？或者其他资料可以贴一下，我尽量完善。

**Comment by ghost** [comment]
https://github.com/IoTChainCode/TokenAirdrop/blob/master/Airdrop/function/airdrop.js#L120
我说的是这里，如果转的是10 decimal的erc20 token 会有问题的。

**Comment by ghost** [comment]
完善了一版你的合约和代码，可以循环发送了，节省了6倍GAS = = 开心。

**Comment by Orangem21** [comment]
可以付费撒

**Comment by saber-yy** [comment]
你指的循环发送是指监听到上一波的交易被确认了就开始发送下一波？

**Comment by ghost** [comment]
是这样的，监听到上一波发送完成就发送下一波。

**Comment by saber-yy** [comment]
这样确实是一个很好的优化。能否共享一下代码？961839401@qq.com。我也再处理一下。

**Comment by ghost** [comment]
可以的 我整理开源给你




获取 Outlook for Android







On Tue, Feb 27, 2018 at 10:09 AM +0800, "saberShenFeng" <notifications@github.com> wrote:












这样确实是一个很好的优化。能否共享一下代码？961839401@qq.com。我也再处理一下。

**Comment by qingduyyy** [comment]
@Orangem21 you could make a commit for the modified edition

**Comment by qt7** [comment]
@Orangem21 im also interested in this development. Please share it with us. This is a great project!
