### ISSUE TITLE
Sometimes

### ISSUE THREAD

**Issue by kameraDevelop** [IoTChainCode/TokenAirdrop#3]

**Comment by kameraDevelop** [comment]
I did all the steps, I downloaded the last code. 

Sometimes it works but only with two wallets

https://etherscan.io/tx/0x91196710882c51be864db33fd70a797f491e5ab0632b27d0369f841622ca08d5

**Comment by saber-yy** [comment]
Sorry, I don't quite understand what you mean. Have you seen README.md?  Or try to modify some parameters to test it.

**Comment by kameraDevelop** [comment]
6( Run approve.js, then your will get the result on console .
7) Config your parameters in config.js ->airdropModule .

why the six step?, why we would run approve.js before seven step?

I dont understand, can you give me an example, why?

**Comment by saber-yy** [comment]
The role of 'approve' is to authorize a transfer with a certain amount of address. If you do not understand 'approve', I suggest that you first understand the concept and role of the approve. You just need to pod install the necessary libraries to run this example on the rinkeby network. I have configured the rinkeby network parameters in my project.
